apiVersion: v1
kind: ConfigMap
metadata:
  name: account
data:
  application.properties: |-
    management.endpoints.web.exposure.include=health,metrics,prometheus,liveness
    opentracing.jaeger.log-spans = true
    logging.config=classpath:logback.xml
    spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
    spring.datasource.url=jdbc:mariadb://maria-svc:3306/kubetv
    spring.datasource.username=root
    spring.datasource.password=Passw0rd
    mybatis.mapper-locations=mybatis/*.xml
    server.port=8090
